name: My First WorkFlow
on:
  push:
    branches:
      - main

jobs:
  myFirstJob:
    runs-on: ubuntu-latest
    steps:
      - name: my first action
        uses: actions/checkout@v6
      - name: my First Step
        run: printenv
      - name: my Second step
        run: |
          echo "Zeev Mindali"
          echo "Hello" > file.txt
          ls
          cat file.txt
      - name: sleeping sleep
        run: sleep 5
      - name: ls repo
        run: |
          ls
      
